name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      matrix:
        description: 'Images to be saved, input as JSON list.'
        required: true
        default: '["alpine:latest"]'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJson(github.event.inputs.matrix) }}

    steps:
    - id: pull_images
      name: Pull Docker Images
      run: |
        echo "Processing image: ${{ matrix.image }}"
          
        # Create a safe filename
        safe_filename=$(echo "${{ matrix.image }}" | sed -e 's/[^A-Za-z0-9._-]/_/g')
          
        echo "Pulling image: ${{ matrix.image }}"
        docker pull "${{ matrix.image }}" --platform "linux/amd64"
          
        echo "Saving image as: ${safe_filename}-amd64.tar"
        docker save "${{ matrix.image }}" -o "${safe_filename}-amd64.tar"
          
        # Add the safe filename to GITHUB_OUTPUT for use in next step
        echo "safe_filename=${{ matrix.image }}" >> $GITHUB_OUTPUT
        done

    - name: Upload Docker image artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.pull_images.outputs.*.safe_filename }}-amd64
        path: ${{ steps.pull_images.outputs.*.safe_filename }}-amd64.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
