name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        safe_names=()
        for image in "${image_array[@]}"; do
          echo "Processing image: $image"
          docker pull "$image" --platform "linux/amd64"
          
          # Create a safe filename
          safe_filename=$(echo "$image" | sed -e 's/[^A-Za-z0-9._-]/_/g')
          safe_names+=("$safe_filename")
          
          echo "Saving image as: ${safe_filename}-amd64.tar"
          docker save "$image" -o "${safe_filename}-amd64.tar"
        done
        
        # Join safe names into a comma-separated string
        safe_names_string=$(IFS=,; echo "${safe_names[*]}")
        echo "SAFE_NAMES=$safe_names_string" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SAFE_NAMES }}.tar
        path: ./*.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
